import org.apache.tools.ant.filters.ReplaceTokens
import work.lclpnet.build.task.GithubDeploymentTask

plugins {
    alias(libs.plugins.java)
    alias(libs.plugins.fabric.loom) apply false
    alias(libs.plugins.gradle.build.utils)
}

Properties props = buildUtils.loadProperties("publish.properties")

group = project.maven_group
version = "${project.mod_version}+${libs.versions.minecraft.get()}"

def modId = project.mod_id
def javaVersion = libs.versions.java.get().toInteger()

base {
    archivesName = modId
}

allprojects {
    apply plugin: libs.plugins.fabric.loom.get().pluginId
    apply plugin: libs.plugins.maven.publish.get().pluginId

    repositories {
        mavenCentral()

        maven {
            url 'https://repo.lclpnet.work/repository/internal'
        }

        maven {
            url 'https://repo.lclpnet.work/repository/snapshots'
        }

        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
                }
            }
            filter {
                includeGroup "maven.modrinth"
            }
        }

        maven {
            url = 'https://maven.nucleoid.xyz/'
        }
    }

    java {
        withSourcesJar()

        sourceCompatibility = JavaVersion.toVersion(javaVersion)
        targetCompatibility = JavaVersion.toVersion(javaVersion)
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release.set(javaVersion)
    }

    processResources {
        def tokens = [
                "version": project.version.toString(),
                "loader_version": libs.versions.fabric.loader.get(),
                "minecraft_compat": project.minecraft_compat,
                "java_version": javaVersion.toString()
        ]

        inputs.properties(tokens)

        filesMatching("fabric.mod.json") {
            expand(tokens)
        }

        filesMatching("*.mixins.json") {
            filter(ReplaceTokens, beginToken: '${', endToken: '}', tokens: tokens)
        }
    }

    [tasks.jar, tasks.sourcesJar].each {
        it.from("LICENSE") {
            rename { "${it}_${project.base.archivesName.get()}" }
        }
    }

    publishing {
        // automatically use DEPLOY_URL, DEPLOY_USER and DEPLOY_PASSWORD environment variables
        // or mavenHost, mavenUser and mavenPassword from props
        buildUtils.setupPublishRepository(repositories, props)
    }
}

sourceSets {
    dev {
        compileClasspath += main.compileClasspath + main.output
        runtimeClasspath += main.runtimeClasspath + main.output
    }
}

dependencies {
    minecraft(libs.minecraft)
    implementation(libs.fabric.loader)
    implementation(libs.fabric.api)

    implementation(libs.kibu)
    implementation(libs.kibu.world.api)
    implementation(libs.fantasy)
    implementation(libs.sqlite.jdbc)
    implementation(libs.gaco)
    implementation(project(":game-api"))
    include(project(":game-api"))

    localRuntime(libs.pal)
    compileOnly(libs.pal)

    // optional runtime mods (and their dependencies, because jar-in-jars are not loaded via dependencies)
    localRuntime(libs.mcserver.api.fabric)
    implementation(libs.translations4j)
    localRuntime(variantOf(libs.translations4j) { classifier("network") })

    compileOnly(libs.jetbrains.annotations)

    implementation(libs.json)

    // include these dependencies
    def includeImpl = { dep ->
        implementation(dep)
        include(dep)
    }

    includeImpl(libs.maze.lib)
    includeImpl(libs.json.config4j)

    // test dependencies
    testImplementation(libs.fabric.loader.junit)
}

loom {
    serverOnlyMinecraftJar()

    runs {
        remove client

        server {
            source "dev"
        }
    }
}

test {
    useJUnitPlatform()
    systemProperty("fabric.side", "server")
}

// add main dependencies to dev source set
configurations.named("devImplementation").configure {
    it.extendsFrom(configurations.implementation)
}

configurations.named("devCompileClasspath").configure {
    it.extendsFrom(configurations.modCompileClasspathMapped)
}

configurations.named("devRuntimeClasspath").configure {
    it.extendsFrom(configurations.modCompileClasspathMapped)
}

// add minecraft dependencies to dev source set (only available after project evaluation)
afterEvaluate {
    configurations.named("devCompileClasspath").get().extendsFrom(configurations.minecraftNamedCompile)
    configurations.named("devRuntimeClasspath").get().extendsFrom(configurations.minecraftNamedRuntime)
}

def env = System.getenv()

tasks.register("github", GithubDeploymentTask) {
    dependsOn tasks.jar

    config {
        token = env.get("GITHUB_TOKEN")
        repository = env.get("GITHUB_REPOSITORY")
    }

    release {
        title = "[${libs.versions.minecraft.get()}] $project.name $project.version"
        tag = project.version
    }

    assets.add(tasks.jar.archiveFile.get())
}

publishing {
    buildUtils.setupPublishRepository(repositories, props)

    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.base.archivesName.get()

            from components.java

            pom {
                name = 'Mini Game Lobby'
                description = 'A mod that introduces a game lifecycle along with a waiting lobby'
            }
        }
    }
}