import net.fabricmc.loom.task.RemapJarTask
import work.lclpnet.build.task.GithubDeploymentTask

plugins {
    alias(libs.plugins.java)
    alias(libs.plugins.fabric.loom)
    alias(libs.plugins.maven.publish)
    alias(libs.plugins.gradle.build.utils)
}

Properties props = buildUtils.loadProperties('publish.properties')

group = project.maven_group
version = "${project.mod_version}+${libs.versions.minecraft.get()}"

def modId = project.mod_id
def javaVersion = libs.versions.java.get().toInteger()

base {
    archivesName = modId
}

repositories {
    mavenCentral()

    maven {
        url 'https://repo.lclpnet.work/repository/internal'
    }

    maven {
        url 'https://repo.lclpnet.work/repository/snapshots'
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }

    maven {
        url = 'https://maven.nucleoid.xyz/'
    }
}

// list of extra source set names that will have minecraft classpath
def extraMcSourceSets = ['activity', 'game', 'dev']
// list of extra source set names that will be available in the main source set
def standaloneSourceSets = ['activity', 'game']
// list of extra source set names that should not be merged into the produced artifacts ("localRuntimeOnly")
def localExtraSourceSets = ['dev']
// list of extra source set names that should have their own standalone jar artifact
def artifactExtraSourceSets = ['activity']

standaloneSourceSets.each {
    sourceSets.register(it).configure {
        // make sourceSet classes available in the main sourceSet
        sourceSets.main.compileClasspath += it.output
    }
}

sourceSets {
    dev {
        compileClasspath += main.compileClasspath + main.output + activity.output + game.output
        runtimeClasspath += main.runtimeClasspath + main.output + activity.output + game.output
    }

    game {
        compileClasspath += activity.output
    }
}

dependencies {
    minecraft(libs.minecraft)
    implementation(libs.fabric.loader)
    implementation(libs.fabric.api)

    implementation("work.lclpnet.mods.kibu:kibu:${project.kibu_version}")
    implementation("work.lclpnet.mods.kibu:kibu-world-api:${project.kibu_world_api_version}")
    implementation(libs.fantasy)
    implementation("maven.modrinth:sqlite-jdbc:3.41.2.1+20230506")
    implementation("work.lclpnet.mods.gaco:gaco:${project.gaco_version}")

    localRuntime("work.lclpnet.mods:pal:${project.pal_version}")
    compileOnly("work.lclpnet.mods:pal:${project.pal_version}")

    // optional runtime mods (and their dependencies, because jar-in-jars are not loaded via dependencies)
    localRuntime("work.lclpnet.mcserver-api:mcserver-api-fabric:${project.mcserver_api_version}")
    implementation("work.lclpnet:translations4j:${project.translations4j_version}")
    localRuntime("work.lclpnet:translations4j:${project.translations4j_version}:network")

    compileOnly('org.jetbrains:annotations:24.1.0')
    gameCompileOnly('org.jetbrains:annotations:24.1.0')
    activityCompileOnly('org.jetbrains:annotations:24.1.0')

    implementation('org.json:json:20231013')
    implementation('com.google.dagger:dagger:2.46.1')
    annotationProcessor('com.google.dagger:dagger-compiler:2.46.1')

    // include these dependencies
    def includeImpl = { dep ->
        implementation(dep)
        include(dep)
    }

    includeImpl('org.apache.commons:commons-compress:1.28.0')
    includeImpl('org.tukaani:xz:1.9')
    includeImpl('org.apache.tika:tika-core:3.2.2')
    includeImpl("work.lclpnet:maze-lib:${project.maze_lib_version}")
    includeImpl('work.lclpnet:json-config4j:1.0.0')

    // test dependencies
    testImplementation(libs.fabric.loader.junit)
    testImplementation('org.junit.jupiter:junit-jupiter-params:5.8.1')
    testImplementation("org.mockito:mockito-core:5.6.0")
}

loom {
    serverOnlyMinecraftJar()

    runs {
        remove client

        server {
            source "dev"
        }
    }
}

test {
    useJUnitPlatform()
    systemProperty("fabric.side", "server")
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.toVersion(javaVersion)
    targetCompatibility = JavaVersion.toVersion(javaVersion)
}

tasks.withType(JavaCompile).configureEach {
    it.options.release.set(javaVersion)
}

[processResources, processDevResources].each {
    def tokens = [
            "version": project.version.toString(),
            "loader_version": libs.versions.fabric.loader.get(),
            "minecraft_compat": project.minecraft_compat,
            "java_version": javaVersion.toString()
    ]

    it.inputs.properties(tokens)

    it.filesMatching("fabric.mod.json") {
        expand(tokens)
    }

    it.filesMatching("*.mixins.json") {
        filter(ReplaceTokens, beginToken: '${', endToken: '}', tokens: tokens)
    }
}

// add main dependencies to the extra sourceSets
extraMcSourceSets.each { name ->
    configurations.named("${name}Implementation").configure {
        it.extendsFrom(configurations.implementation)
    }

    configurations.named("${name}CompileClasspath").configure {
        it.extendsFrom(configurations.modCompileClasspathMapped)
    }

    configurations.named("${name}RuntimeClasspath").configure {
        it.extendsFrom(configurations.modCompileClasspathMapped)
    }

    // add minecraft dependencies to extra sourceSet (only available after project evaluation)
    afterEvaluate {
        configurations.named("${name}CompileClasspath").get().extendsFrom(configurations.minecraftNamedCompile)
        configurations.named("${name}RuntimeClasspath").get().extendsFrom(configurations.minecraftNamedRuntime)
    }

    def set = sourceSets.named(name).get()

    sourceSets.named('test').configure {
        it.compileClasspath += set.output
        it.runtimeClasspath += set.output
    }

    if (!localExtraSourceSets.contains(name)) {
        tasks.named("process${name.capitalize()}Resources").configure {
            tasks.processResources.dependsOn(it)  // should process activity resources
        }

        // include extra sourceSet in main jar tasks
        jar {
            from set.output
        }

        sourcesJar {
            from set.allSource
        }
    }
}

def licenseJarTasks = [jar, sourcesJar]

artifactExtraSourceSets.each { name ->
    // add extra jar tasks
    def jar = tasks.register("${name}Jar", Jar.class) {
        from(sourceSets.named(name).get().output)

        description "Builds the standalone ${name} api jar."
        group 'build'
    }.get()

    tasks.assemble.dependsOn(jar)

    licenseJarTasks.add(jar)
}

// include license file in jar tasks
licenseJarTasks.each {
    it.from('LICENSE') {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}

def env = System.getenv()

tasks.register("github", GithubDeploymentTask) {
    dependsOn tasks.jar

    config {
        token = env.get("GITHUB_TOKEN")
        repository = env.get("GITHUB_REPOSITORY")
    }

    release {
        title = "[${libs.versions.minecraft.get()}] $project.name $project.version"
        tag = project.version
    }

    assets.add(tasks.jar.archiveFile.get())
}

publishing {
    buildUtils.setupPublishRepository(repositories, props)

    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.base.archivesName.get()

            from components.java

            pom {
                name = 'Mini Game Lobby'
                description = 'A mod that introduces a game lifecycle along with a waiting lobby'
            }
        }
    }
}